name:                json-fleece-hermes
version:             0.2.0.0
github:              "flipstone/json-fleece/json-fleece-hermes"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/flipstone/json-fleece-hermes#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11 && < 0.12
- json-fleece-core >= 0.8 && < 0.9
- text >= 2.0 # This could be problematic for anyone using LTS 20 or below

flags:
  strict:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(strict)
    then:
      ghc-options:
        - -Weverything
        - -Werror
        - -Wno-missing-local-signatures
        - -Wno-monomorphism-restriction
        - -Wno-missing-kind-signatures
        - -Wno-prepositive-qualified-module
        - -Wno-implicit-prelude
        - -Wno-safe
        - -Wno-unsafe
        - -Wno-missing-safe-haskell-mode
        - -Wno-missing-deriving-strategies
        - -Wno-all-missed-specialisations
        - -Wno-missed-specialisations
        - -Wno-unticked-promoted-constructors
    else:
      ghc-options:
        - -Wall
library:
  source-dirs: src
  exposed-modules:
    - Fleece.Hermes
  dependencies:
    - containers >= 0.6 && < 0.7
    - hermes-json >= 0.6 && < 0.7
    - shrubbery >= 0.2 && < 0.3

tests:
  json-fleece-hermes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >= 2.0 && < 2.2
    - containers >= 0.6 && < 0.7
    - json-fleece-hermes
    - json-fleece-examples
    - hedgehog
    - scientific >= 0.3.7 && < 0.4
    - shrubbery >= 0.2 && < 0.3
    - time >= 1.11 && < 1.13
    - vector >= 0.12 && < 0.14

benchmarks:
  json-fleece-hermes-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - aeson >= 2.0
      - base
      - bytestring
      - deepseq
      - hermes-json
      - json-fleece-aeson
      - json-fleece-hermes
      - text
      - tasty-bench
    default-extensions: OverloadedStrings
    ghc-options:
      - -Wall
      - -rtsopts
      - -with-rtsopts=-T +RTS -A32m -RTS
