resolver: lts-22.39
system-ghc: true
install-ghc: false

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- json-fleece-core
- json-fleece-examples
- json-fleece-aeson
- json-fleece-aeson-beeline
- json-fleece-markdown
- json-fleece-codegen-util
- json-fleece-openapi3
- json-fleece-swagger2
- json-fleece-pretty-print
- json-fleece-hermes
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#

# Override default flag values for local packages and extra-deps
flags:
  json-fleece-core:
    strict: true

  json-fleece-examples:
    strict: true

  json-fleece-aeson:
    strict: true

  json-fleece-aeson-beeline:
    strict: true

  json-fleece-markdown:
    strict: true

  json-fleece-codegen-util:
    strict: true

  json-fleece-openapi3:
    strict: true

  json-fleece-swagger2:
    strict: true

  json-fleece-pretty-print:
    strict: true

  json-fleece-hermes:
    strict: true

extra-deps:
  - github: flipstone/beeline
    commit: 6f4d696469463ed892249074dbaf3fa96f145685
    subdirs:
      - beeline-routing
      - beeline-http-client
  - github: flipstone/shrubbery
    commit: 95c5bf28d03ed8b4df163a98b878fa515bf40604
  - hermes-json-0.6.1.0@sha256:ab54609e63a83a8e07900360de60ba1e197ea499fa5d3eb782eed980ee07545b,3856


# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of Stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.9"
#
# Override the architecture used by Stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by Stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
