# We test examples against the *oldest* lts that the libraries support
resolver: lts-21.22
packages:
- .
extra-deps:
  - ../../../json-fleece-core
  - ../../../json-fleece-aeson
  - ../../../json-fleece-aeson-beeline
  - github: flipstone/beeline
    commit: ad51a5197ba71b44f27fd760c6c241ac67f0a52f
    subdirs:
      - beeline-params
      - beeline-routing
      - beeline-http-client
  - github: flipstone/shrubbery
    commit: a064ede07e01b753a6eb310fc24d9fd8da1ad826
  - non-empty-text-0.2.1@sha256:df9629af4ad53af59dc0bfb5995c0500aaa656c884485560e9115152f7495c20,2438
