name:                json-fleece-openapi3
version:             0.4.6.2
github:              "flipstone/json-fleece/json-fleece-openapi3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flipstone/json-fleece-openapi3#readme>
tested-with:
    GHC == 9.4.8, GHC == 9.6.7, GHC == 9.8.4, GHC == 9.10.2

flags:
  strict:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(strict)
    then:
      ghc-options:
        - -Weverything
        - -Werror
        - -Wno-missing-local-signatures
        - -Wno-monomorphism-restriction
        - -Wno-missing-kind-signatures
        - -Wno-prepositive-qualified-module
        - -Wno-implicit-prelude
        - -Wno-safe
        - -Wno-unsafe
        - -Wno-missing-safe-haskell-mode
        - -Wno-missing-deriving-strategies
        - -Wno-all-missed-specialisations
        - -Wno-missed-specialisations
        - -Wno-unticked-promoted-constructors
      when:
        - condition: impl (ghc >= 9.8)
          ghc-options:
            - -Wno-missing-role-annotations
            - -Wno-missing-poly-kind-signatures
        - condition: impl (ghc >= 9.10)
          ghc-options:
            - -Wno-defaulted-exception-context
    else:
      ghc-options:
        - -Wall

dependencies:
  - base >= 4.7 && < 5
  - json-fleece-codegen-util >= 0.13 && < 0.14

extra-source-files:
  - examples/star-trek/codegen.dhall
  - examples/star-trek/star-trek.yaml
  - examples/star-trek/StarTrek/**/*.hs
  - examples/test-cases/codegen.dhall
  - examples/test-cases/test-cases.yaml
  - examples/test-cases/TestCases/**/*.hs

library:
  source-dirs: src
  exposed-modules:
    - Fleece.OpenApi3
  dependencies:
    - aeson >= 2.0 && < 2.3
    - insert-ordered-containers >= 0.2 && < 0.3
    - containers >= 0.6 && < 0.8
    - mtl >= 2.2 && < 2.4
    - non-empty-text >= 0.2 && < 0.3
    - openapi3 >= 3.2 && < 3.3
    - text >= 1.2 && < 2.2

executables:
  fleece-openapi3:
    main: Main.hs
    source-dirs: exe
    ghc-options:
      - -rtsopts
      - -threaded
    dependencies:
      - json-fleece-openapi3

tests:
  json-fleece-openapi3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - json-fleece-openapi3
      - hedgehog
      - bytestring >= 0.11 && < 0.13
      - file-embed >= 0.0.15 && < 0.0.17
      - yaml >= 0.11 && < 0.12
