#!/usr/bin/env bash

set -e

source scripts/lib/run-in-container.sh

./scripts/format-repo

# This includes testing that the code-gen libraries generate code that
# matches the previously generated code for the examples. This script
# does _not_ automatically re-generate the examples to avoid un-intentional
# changes since we use the examples as golden tests this.
#
# Use ./scripts/generate-examples if you intend to generate new example code
# because you've altered the code gen.
./scripts/test-all


# Check the that examples still compile with the latest fleece code.
./scripts/test-examples
