#!/usr/bin/env bash

set -e

source scripts/lib/run-in-container.sh

if [ "$CI" ]; then
  MODE=check
else
  MODE=inplace
fi

find */* -iname '*.hs' \
  | grep -v openapi3/examples \
  | xargs fourmolu --mode $MODE
