#!/usr/bin/env bash

set -e

source scripts/lib/run-in-container.sh

STACK_OPTIONS=""

if [ "$CI" ]; then
  STACK_OPTIONS="--lock-file error-on-write"
else
  STACK_OPTIONS="--fast"
fi

(cd json-fleece-openapi3/examples/test-cases && stack build $STACK_OPTIONS "$@")
(cd json-fleece-openapi3/examples/star-trek && stack build $STACK_OPTIONS "$@")
(cd json-fleece-swagger2/examples/uber && stack build $STACK_OPTIONS "$@")
