name:                uber
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/uber#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2023 Author name here
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - text
  - scientific
  - json-fleece-core >= 0.1.3 && < 0.8
  - json-fleece-aeson-beeline >= 0.2 && < 0.3
  - beeline-routing >= 0.2.4 && < 0.3
  - beeline-http-client >= 0.8 && < 0.9
  - time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: .
